name: "atlas_recal"
description: gives an estimation of the sequencing bias based on known invariant sites 
keywords:
  - sequencing_bias
  - ATLAS
tools:
  - "atlas":
      description: "ATLAS, a suite of methods to accurately genotype and estimate genetic diversity"
      homepage: "https://bitbucket.org/wegmannlab/atlas/wiki/Home"
      documentation: "https://bitbucket.org/wegmannlab/atlas/wiki/Home"
      tool_dev_url: "None"
      doi: "https://doi.org/10.1101/105346"
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - empiric:
      type: file
      description: txt file from PMD estimations
      pattern: "*.txt"
  - fasta: 
      type: file
      description: fasta reference file
      pattern: "*.{fasta,fa}"
  -alleles:
      type: file
      descrition: A bed file with invariant site coordinates created by user 
      pattern: "*.bed"


output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - recal_patterns:
      type: file
      description: file containing the sequencing bias for each of the Read Group pools 
      pattern: "*.txt

authors:
  - "@ltcrod"